#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := iot_mecanum_car_iot_soc

EXTRA_COMPONENT_DIRS = $(IDF_PATH)/examples/common_components/iot_mecanum_car_iot_soc

include $(IDF_PATH)/make/iot_mecanum_car_iot_soc.mk
